### ISSUE TITLE
E2e tests on CLI failing due to the libdbus-1-dev dep

### ISSUE THREAD

**Issue by sagpatil** [stellar/system-test#116]
E2e tests are still failing due to the libdbus-1-dev dep
Docker file already has the dependency, but maybe we need to release docker images? https://github.com/stellar/system-test/commit/5df600c05fc97b0c77b2c458d3929a633ca6c196

example failure : https://github.com/stellar/stellar-cli/actions/runs/12914641438/job/36014676372

**Comment by sreuland** [comment]
Is this still open issue, it looked a related fix was merged - https://github.com/stellar/system-test/pull/109

**Comment by sagpatil** [comment]
yes seems like the fix didnt work as expected and the test are still failing.
